// <auto-generated />
using System;
using FiTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiTrack.Api.Migrations
{
    [DbContext(typeof(FiTrackDbContext))]
    [Migration("20260308141937_AddWeightLogs")]
    partial class AddWeightLogs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiTrack.Api.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passcode_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasscodeHash = "AQAAAAIAAYagAAAAEMOCK8GkM8J7W0X0dM5mA3O3Nn7Q3qV2Pq1r0J9G4k8x6mVh2Qq8qP1p4L5j9A==",
                            UpdatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "demo_user"
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("CurrentWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("current_weight");

                    b.Property<int?>("DailyCalorieGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_calorie_goal");

                    b.Property<int?>("DailyCarbGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_carb_goal");

                    b.Property<int?>("DailyFatGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_fat_goal");

                    b.Property<int?>("DailyProteinGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_protein_goal");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WeeklyExerciseGoal")
                        .HasColumnType("int")
                        .HasColumnName("weekly_exercise_goal");

                    b.Property<int?>("WeightGoal")
                        .HasColumnType("int")
                        .HasColumnName("weight_goal");

                    b.HasKey("UserId");

                    b.ToTable("tbl_user_profile", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique();

                    b.ToTable("tbl_weight_logs", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserProfile", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FiTrack.Api.Models.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.WeightLog", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.User", b =>
                {
                    b.Navigation("Profile");

                    b.Navigation("WeightLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
