// <auto-generated />
using System;
using FiTrack.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FiTrack.Api.Migrations
{
    [DbContext(typeof(FiTrackDbContext))]
    [Migration("20260308182904_AddWorkoutSessions")]
    partial class AddWorkoutSessions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FiTrack.Api.Models.Food.Food", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbs")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("carbs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Fat")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("fat");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<decimal>("Protein")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("protein");

                    b.Property<string>("ServingDescription")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("serving_description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name");

                    b.ToTable("tbl_foods", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.FoodLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Calories")
                        .HasColumnType("int")
                        .HasColumnName("calories");

                    b.Property<decimal>("Carbs")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("carbs");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal>("Fat")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("fat");

                    b.Property<int?>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("logged_at");

                    b.Property<int?>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("meal_id");

                    b.Property<string>("MealSlot")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("meal_slot");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("note");

                    b.Property<decimal>("Protein")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("protein");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("source_type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.HasIndex("UserId", "LogDate");

                    b.HasIndex("UserId", "LoggedAt");

                    b.ToTable("tbl_food_logs", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_food_logs_meal_slot", "[meal_slot] IS NULL OR [meal_slot] IN ('breakfast', 'lunch', 'dinner', 'snack')");

                            t.HasCheckConstraint("CK_tbl_food_logs_source_type", "[source_type] IN ('food', 'meal', 'custom')");
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.Meal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsFavorite")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_favorite");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.ToTable("tbl_meals", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.MealItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("FoodId")
                        .HasColumnType("int")
                        .HasColumnName("food_id");

                    b.Property<int>("MealId")
                        .HasColumnType("int")
                        .HasColumnName("meal_id");

                    b.Property<decimal>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)")
                        .HasDefaultValue(1m)
                        .HasColumnName("quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.HasIndex("MealId", "FoodId")
                        .IsUnique();

                    b.ToTable("tbl_meal_items", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.ExerciseCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyPart")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("body_part");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("ExerciseType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("exercise_type");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BodyPart");

                    b.HasIndex("ExerciseType");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("lkp_exercise_catalog", null, t =>
                        {
                            t.HasCheckConstraint("CK_lkp_exercise_catalog_body_part", "[body_part] IS NULL OR [body_part] IN ('chest', 'shoulders', 'bicep', 'tricep', 'back', 'legs', 'core')");

                            t.HasCheckConstraint("CK_lkp_exercise_catalog_exercise_type", "[exercise_type] IN ('compound', 'accessory')");
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("MuscleFocus")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("muscle_focus");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "Name")
                        .IsUnique();

                    b.HasIndex("UserId", "SortOrder");

                    b.ToTable("tbl_workout_days", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutDayExercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("CurrentWorkingWeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("current_working_weight");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int")
                        .HasColumnName("exercise_id");

                    b.Property<int>("ExerciseOrder")
                        .HasColumnType("int")
                        .HasColumnName("exercise_order");

                    b.Property<decimal?>("InitialWeight")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)")
                        .HasColumnName("initial_weight");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<int>("TargetRepsMax")
                        .HasColumnType("int")
                        .HasColumnName("target_reps_max");

                    b.Property<int>("TargetRepsMin")
                        .HasColumnType("int")
                        .HasColumnName("target_reps_min");

                    b.Property<int>("TargetSets")
                        .HasColumnType("int")
                        .HasColumnName("target_sets");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("int")
                        .HasColumnName("workout_day_id");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutDayId");

                    b.HasIndex("WorkoutDayId", "ExerciseOrder")
                        .IsUnique();

                    b.ToTable("tbl_workout_day_exercises", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_workout_day_exercises_exercise_order", "[exercise_order] > 0");

                            t.HasCheckConstraint("CK_tbl_workout_day_exercises_target_reps_max", "[target_reps_max] > 0");

                            t.HasCheckConstraint("CK_tbl_workout_day_exercises_target_reps_min", "[target_reps_min] > 0");

                            t.HasCheckConstraint("CK_tbl_workout_day_exercises_target_reps_range", "[target_reps_max] >= [target_reps_min]");

                            t.HasCheckConstraint("CK_tbl_workout_day_exercises_target_sets", "[target_sets] > 0");
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateOnly>("SessionDate")
                        .HasColumnType("date")
                        .HasColumnName("session_date");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("session_name");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("WorkoutDayId")
                        .HasColumnType("int")
                        .HasColumnName("workout_day_id");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkoutDayId");

                    b.HasIndex("UserId", "SessionDate");

                    b.HasIndex("UserId", "StartedAt");

                    b.ToTable("tbl_workout_sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_tbl_workout_sessions_status", "[status] IN ('in_progress', 'completed', 'cancelled')");
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("PasscodeHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("passcode_hash");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("tbl_users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            PasscodeHash = "AQAAAAIAAYagAAAAEMOCK8GkM8J7W0X0dM5mA3O3Nn7Q3qV2Pq1r0J9G4k8x6mVh2Qq8qP1p4L5j9A==",
                            UpdatedAt = new DateTime(2026, 3, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "demo_user"
                        });
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserGoalsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int?>("DailyCalorieGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_calorie_goal");

                    b.Property<int?>("DailyCarbGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_carb_goal");

                    b.Property<int?>("DailyFatGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_fat_goal");

                    b.Property<int?>("DailyProteinGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_protein_goal");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_from");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_to");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<int?>("WeeklyExerciseGoal")
                        .HasColumnType("int")
                        .HasColumnName("weekly_exercise_goal");

                    b.Property<decimal?>("WeightGoal")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight_goal");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("UserId", "EffectiveFrom");

                    b.ToTable("tbl_user_goals_history", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal?>("CurrentWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("current_weight");

                    b.Property<int?>("DailyCalorieGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_calorie_goal");

                    b.Property<int?>("DailyCarbGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_carb_goal");

                    b.Property<int?>("DailyFatGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_fat_goal");

                    b.Property<int?>("DailyProteinGoal")
                        .HasColumnType("int")
                        .HasColumnName("daily_protein_goal");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WeeklyExerciseGoal")
                        .HasColumnType("int")
                        .HasColumnName("weekly_exercise_goal");

                    b.Property<int?>("WeightGoal")
                        .HasColumnType("int")
                        .HasColumnName("weight_goal");

                    b.HasKey("UserId");

                    b.ToTable("tbl_user_profile", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.WeightLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("LogDate")
                        .HasColumnType("date")
                        .HasColumnName("log_date");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("logged_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "LogDate")
                        .IsUnique();

                    b.ToTable("tbl_weight_logs", (string)null);
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.Food", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("Foods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.FoodLog", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Food.Food", "Food")
                        .WithMany("FoodLogs")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FiTrack.Api.Models.Food.Meal", "Meal")
                        .WithMany("FoodLogs")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("FoodLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.Meal", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("Meals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.MealItem", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Food.Food", "Food")
                        .WithMany("MealItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiTrack.Api.Models.Food.Meal", "Meal")
                        .WithMany("MealItems")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Food");

                    b.Navigation("Meal");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutDay", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutDayExercise", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Gym.ExerciseCatalog", "ExerciseCatalog")
                        .WithMany("WorkoutDayExercises")
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FiTrack.Api.Models.Gym.WorkoutDay", "WorkoutDay")
                        .WithMany("WorkoutDayExercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExerciseCatalog");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutSession", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FiTrack.Api.Models.Gym.WorkoutDay", "WorkoutDay")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("User");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserGoalsHistory", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("GoalsHistory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.UserProfile", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithOne("Profile")
                        .HasForeignKey("FiTrack.Api.Models.Users.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.WeightLog", b =>
                {
                    b.HasOne("FiTrack.Api.Models.Users.User", "User")
                        .WithMany("WeightLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.Food", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Food.Meal", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("MealItems");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.ExerciseCatalog", b =>
                {
                    b.Navigation("WorkoutDayExercises");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Gym.WorkoutDay", b =>
                {
                    b.Navigation("WorkoutDayExercises");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("FiTrack.Api.Models.Users.User", b =>
                {
                    b.Navigation("FoodLogs");

                    b.Navigation("Foods");

                    b.Navigation("GoalsHistory");

                    b.Navigation("Meals");

                    b.Navigation("Profile");

                    b.Navigation("WeightLogs");

                    b.Navigation("WorkoutDays");

                    b.Navigation("WorkoutSessions");
                });
#pragma warning restore 612, 618
        }
    }
}
